# Generated by Django 3.1.5 on 2021-01-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogthemes',
            name='description',
            field=models.CharField(default='', max_length=150, verbose_name='Краткое описание'),
        ),
    ]
