# Generated by Django 3.1.5 on 2021-02-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogthemes_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogthemes',
            name='show_on_main',
            field=models.BooleanField(default=True, verbose_name='Показывать на главной'),
        ),
    ]
