# Generated by Django 3.1.6 on 2021-02-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210209_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloghomepage',
            name='body',
        ),
    ]
