# Generated by Django 3.1.14 on 2022-06-18 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('blog', '0011_remove_bloghomepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogthemes',
            name='locale',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
        ),
        migrations.AddField(
            model_name='blogthemes',
            name='translation_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='blogthemes',
            unique_together={('translation_key', 'locale')},
        ),
    ]
