# Generated by Django 3.1.14 on 2022-06-18 05:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('blog', '0013_auto_20220618_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogthemes',
            name='locale',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogthemes',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
