# Generated by Django 3.1.14 on 2022-06-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20220618_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogthemes',
            name='description_en',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='blogthemes',
            name='description_ru',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='blogthemes',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название темы'),
        ),
        migrations.AddField(
            model_name='blogthemes',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название темы'),
        ),
    ]
