# Generated by Django 3.1.14 on 2022-06-29 09:57

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_ru',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
